---
# - hosts: all
- hosts: webservers
  become: yes
  tasks:
    - name: I want to install wget on only ubuntu nodes
      apt:
        name: "{{webapponubuntu}}"
        state: present
      when: ansible_os_family=="Debian"  

    - name: I want to install webserver on redhad nodes
      dnf:
        name: "{{webapponamazon}}"
        state: present
        when: ansible_os_family=="RedHat"
          
