---
# - hosts: all
- hosts: webservers
  become: yes
  tasks:
    - name: I want to install apache2 on only ubuntu nodes
      apt:
        name: apache2 #"{{webapponubuntu}}"
        state: absent
        when: ansible_os_family=="Debian"

    # - name: I want to start "{{webapponamazon}}"
    #   service:
    #     name: "{{webapponamazon}}"
    #     state: started
    #     when: ansible_os_family=="Debian"      

    # - name: I want to install "{{webapponamazon}}" on redhad nodes
    #   dnf:
    #     name: "{{webapponamazon}}"
    #     state: present
    #     when: ansible_os_family=="RedHat"
          
