---
- hosts: all
  become: yes
  tasks:
    - name: I want to install wget on only ubuntu nodes
      apt:
        name: wget
        state: absent
      when: ansible_os_family=="Debian"  

    - name: I want to install webserver on redhad nodes
      dnf:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"    