---
- hosts: all
  become: yes
  tasks:
    - name: i want to install git on ansible nodes #apt-get insatll
      apt:
        name: apahce2
        state: present #prsent-install and absent-uninstall
        
