---
- hosts: all
  become: yes
  tasks:
    - name: i want to install apache2 on ansible nodes #apt-get insatll
      apt:
        name: apache2
        state: absent  #prsent-install and absent-uninstall
    # - name: I want to start the server
    #   service:
    #     name: apache2
    #     state: started
      
