---
- hosts: all
  become: yes
  tasks:
    - name: I want to install tree
      apt:
        name: tree
        state: present
    - name: I want uninstall tree
      apt: tree
      state: absent
      